### ISSUE TITLE
Add an option for blank time

### ISSUE THREAD

**Issue by pickfire** [Webconverger/rpi2#3]
The current purposed format is `Fri 2012-11-23 11:12:13 +10h` based on [`systemd.time(7)`](https://www.freedesktop.org/software/systemd/man/systemd.time.html), explaination:
- Day of week `Fri`
  - Or probably it can be `Mon-Fri`
- Date `YY-MM-DD`
  - **Always required if day of week not specified**
- Starting time `HH:MM:SS`
  - Defaults to **0** if unspecified
  - Hour in 24h format
- Duration `+DdHhMmSs`
  - Defaults to **nothing** if unspecified

@kaihendry Any idea on this?

Currently weakness:
- Multiple blank time, e.g. separation for **weekdays** and **weekends**.

More info at https://wiki.archlinux.org/index.php/Systemd/Timers

**Comment by kaihendry** [comment]
Can you flesh out some examples for some typical use cases.

Note you cannot use `blank=` since that is already used in https://webconverger.org/blanking/

Maybe best to use something like `wake=`

So lets say we want the screen to visible between the working days & hours of 9AM to 6PM. Otherwise it blanks about 10 minutes of inactivity.

```
blank=10
wake=Mon-Fri 09:00:00 +9h
```

WDYT?

**Comment by pickfire** [comment]
Sorry for the late reply.

Oh, I didn't notice `blank=` is already in use.

I guess I can make `wake=` is nice too (well the code can be reused) but one thing:
- One can use timer to wake screen up **only** in weekdays.
- One **cannot** use time to wake screen up in weekdays in conjunction with a different timing due to the limitations of `systemd.time` IIRC.
- There is some ways to overcome, I need to recheck if one can use multiple timers.

A typical use case is like the one like you showed. But as you said, there is an unknown limitation of the web config that disables the use of spaces.

**Comment by kaihendry** [comment]
It's a known limitation. The first paragraph of https://webconverger.org/api you will see I ask to `encodeURI` API lines that have spaces.

**Comment by pickfire** [comment]
I get it now, I guess I just need to escape it with maybe something like `,`.

**Comment by kaihendry** [comment]
No your escape with the Web standard function of 

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/encodeURI

& decode with

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI

In my script IIRC i use some bash function implementation or busybox
httpd decode function to do this.

**Comment by pickfire** [comment]
Ah, I get it now. I guess I can just use `sed` to revert it to spaces.

But it might have some bad effects for someone else, just in case they say that `&20` and stop submitting.

**Comment by pickfire** [comment]
@kaihendry This is solved in the latest release on the `wake` branch, feel free to merge it.
