### ISSUE TITLE
Add support for East Asian fonts

### ISSUE THREAD

**Issue by thwpike** [Webconverger/rpi2#4]
Thank you for providing webconverger on the Raspberry Pi.  Would it be possible to include support for east Asian fonts including Chinese Traditional and Simplified?

**Comment by kaihendry** [comment]
I guess that is Noto Sans @pickfire ?

**Comment by pickfire** [comment]
@kaihendry Nope, it is either `wqy-microhei` (for phone, maybe works too) or `wqy-zenhei` (the one I am using).

If you want chinese input too, I suggest to install `fcitx`, small and light-weight. The alternative is `ibus`.

I will work on this.

**Comment by pickfire** [comment]
@thwpike This is implemented and tested in 7c1754d. @kaihendry I am currently working in setting up fcitx. Do you plan to include it (it probably requires gtk2)?

**Comment by pickfire** [comment]
@thwpike, this is merged in master in commit `7c1754d`. I will be closing this issue.
