### ISSUE TITLE
Slow to boot

### ISSUE THREAD

**Issue by kaihendry** [Webconverger/rpi2#5]
http://s.natalian.org/2016-03-30/slow.txt

bde06b3 runs systemd 219-6. Be good to upgrade that.

**Comment by pickfire** [comment]
I will upgrade rpi2 to new newest systemd 229-3 in the `jsbroken` branch as the javascript is still currently broken, I will be here later after I found a version of java that is working on my computer.
- `instantupdate` isn't in rpi. It should be added.

One thing is weird, seems like surf2.service isn't there, need to check it.
