### ISSUE TITLE
Video playback is really slow

### ISSUE THREAD

**Issue by Lennaert** [Webconverger/rpi2#6]
Hello!

HTML5 <video> (mp4) tags are not running smooth at all. 
The refresh rate is very small, it's like I'm on a remote desktop through VNC or something.

For example, when I try http://youtube.com (or any other HTML5 video website), the video playback is not smooth at all. 

Is it just a setting? Is it Xorg?

Thank  you!

**Comment by pickfire** [comment]
@Lennaert The video playback in the new webkit is not patched with video acceleration like how the old webkit was patched. More info about that http://dabase.com/blog/Webkit_on_Rpi2/

If you only need to play video (again and again), it is better to do it with omxplayer in the config:

```
homepage=http://domain.tld/video1.mp4 http://domain.tld/video2.mp4
chrome=omxplayer
```

The youtube video url can be taken from output of `yturl` or `youtube-dl -g` or `you-get -i` or something similar.

**Comment by Lennaert** [comment]
Thank you for the information @pickfire 

I've installed the 'midori' browser (http://midori-browser.org/). It's also based on Webkit and it's using GSStreamer for HTML5 video playback

This browser does a better job on some videos, not all, I guess it depends on the encoding of the video. But for example youtube is running very smooth now.

It can also run chromeless and full screen:
midori -e Fullscreen -a https://www.youtube.com

**Comment by kaihendry** [comment]
hmm, wonder if Midori is using  WebKitGTK+ 2.x from https://webkitgtk.org/ or something really ancient?!

**Comment by pickfire** [comment]
@kaihendry Midori uses webkitgtk.

@Lennaert Midori is using the same engine as surf1 but it's surf2 (using webkitgtk2) here on rpi that is installed IIRC.

**Comment by Lennaert** [comment]
It wasn't a success in the end though. I had to update all packages dependencies from hell and then things were breaking and the booting took ages... So I had to rewind everything.

So is there any solution for this HTML5 video playback? Running omxplayer is not really an option, I would like to run html5 videos in the browser. Or is this a 'wont-fix' due to the new webkit?

**Comment by pickfire** [comment]
@Lennaert I tried updating everything, it isn't nice too, it's still broken.

But if you insist, I think firefox plays video better, maybe you can try out firefox (since it's using gecko). It seems faster than webkit-based browser IMHO.

The webkit is a 'wont-fix' for now since we need to wait for the webkit dev to patch them.

**Comment by Lennaert** [comment]
Thank you @pickfire 
Then feel free to close the issue!
