### ISSUE TITLE
README has issues

### ISSUE THREAD

**Issue by kaihendry** [Webconverger/rpi2#9]
`sudo su` could be just `sudo -i`

I'm not sure I like the `<E> <E>` instructions since you are missing one whilst creating the linux partition I think.

http://s.natalian.org/2016-11-23/setup.txt

If my `sd=/dev/mmcblk0` is, my first partition could be `/dev/mmcblk0p1` & `/dev/mmcblk0p2` not, `${sd}1` & `${sd}2` as the readme suggests, since it misses the **p**.

**Comment by pickfire** [comment]
@kaihendry Okay, I will send in a pull request for the `sudo -i`. Maybe I will just use `Enter` instead of `<E>`.

For the `sd=/dev/mmcblk0`, I think i will create a wildcard for it since someone might use `${sd}1` in which I did. (sd card over usb adapter)

What do you think?

**Comment by pickfire** [comment]
The reason why I do `<E>` is that I left some lines empty.
